# Container for hosting dev.blues.io locally

# Build development environment
# $ docker build . --tag dev.blues.io

# Launch development environment
# $ docker run --interactive --net host --rm --tty \
#   --volume $(pwd):/var/www/ dev.blues.io

# Define global arguments
ARG DEBIAN_FRONTEND="noninteractive"

# Base Image
FROM node:16.14-slim

# Import global arguments
ARG DEBIAN_FRONTEND

# Execution Environment
RUN ["dash", "-c", "\
    apt-get update --quiet \
 && apt-get install --assume-yes --no-install-recommends --quiet \
      bash \
      ca-certificates `# for yarn install from git` \
      git \
      nano     `# for git commit --amend` \
      ssh      `# for git push` \
 && apt-get clean \
 && apt-get purge \
 && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
"]

# Runtime Environment
WORKDIR /var/www/

# Set default launch command
CMD ["bash"]
