[build]
  command = "sed -i \"s|process.env.DEPLOY_URL|'${DEPLOY_URL}'|g\" config.ts && yarn build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[template.environment]
  NEXT_PUBLIC_COMPANY_NAME = "Company Name for Header"
  HUB_DEVICE_UID= "Device UID of the "
  HUB_PROJECTUID = "Project UID of your Notehub Project. e.g. app:11111111-1111-1111-1111-111111111111"
  HUB_AUTH_TOKEN = "Notehub API Authentication Token"
  HUB_BASE_URL = "(optional) Base URL representing the Notehub API"
  DEBUG_CONFIG = "(optional) Debug config? If not '', log environment and config on the server"
