[build]
  command = "yarn build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[template.environment]
  NEXT_PUBLIC_COMPANY_NAME = "Company Name for Header"
  HUB_BASE_URL = "Base URL representing the Notehub API (optional)"
  HUB_AUTH_TOKEN = "Notehub API Authentication Token"
  HUB_APP_UID = "App UID of your Notehub Project"
