import Head from "next/head";
import LayoutComponent from "../components/Layout";
import "../styles/globals.css";

require("../styles/antd-variables.less");

const MyApp = function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Sparrow Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
      </Head>
      <LayoutComponent>
        <Component {...pageProps} />
      </LayoutComponent>
    </>
  );
};

export default MyApp;
