import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sparrow Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Sparrow Starter</h1>
        <ul>
          <li><Link href="/12345">Gateway 12345 Summary Page</Link></li>
          <li><Link href="/12345/details">Gateway 12345 Details Page</Link></li>
          <li><Link href="/12345/sensor/67890">Sensor 67890 Summary Page</Link></li>
          <li><Link href="/12345/sensor/67890/details">Sensor 67890 Details Page</Link></li>
        </ul>
      </main>
    </div>
  );
};

export default Home;
